[tool.mypy]
python_version = "3.11"
strict = true
plugins = ["pydantic.mypy"]
warn_unused_configs = true
exclude = [
    "(?x)(^tmp/|^.venv/|^venv/|^dist/|^build/|^.eggs/|^__pycache__/|.*\\.egg-info/|^.pytest_cache/|^.git/|^node_modules/)"
]

[[tool.mypy.overrides]]
module = "uuid_utils.*"
ignore_missing_imports = true
